project:
  type: default
  output-dir: "_output"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    embed-resources: true

execute:
  echo: false
  warning: false
  error: false
  cache: false