# GitHub Actions CI for Shut the Box (shut_the_box_sim)
# Runs Rye-managed lint, typecheck, and test (with coverage) on push/PR.
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12.9"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python (pre-warm for Rye)
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Rye
        uses: eifinger/setup-rye@v3
      - name: Sync dependencies with Rye
        run: rye sync
        working-directory: shut_the_box_sim
      - name: Install test system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-dev
      - name: Show Rye version
        run: rye --version
        working-directory: shut_the_box_sim
      - name: Lint
        run: rye run lint
        working-directory: shut_the_box_sim
      - name: Typecheck
        run: rye run typecheck
        working-directory: shut_the_box_sim
      - name: Test (with coverage)
        run: rye run test-cov
        working-directory: shut_the_box_sim
      - name: CLI smoke test
        run: rye run python -m stbsim.cli --n-games 10 --p1-strategy greedy_max --p2-strategy min_tiles --seed 123
        working-directory: shut_the_box_sim
      - name: Upload coverage html report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-python${{ matrix.python-version }}
          path: shut_the_box_sim/reports/coverage_html/

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python (matches project .python-version)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.9"
      - name: Setup Rye
        uses: eifinger/setup-rye@v3
      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Sync dependencies
        run: rye sync
        working-directory: shut_the_box_sim
      - name: Render Quarto analysis report
        run: |
          cd analysis
          QUARTO_PYTHON=../shut_the_box_sim/.venv/bin/python quarto render strategy_comparison_basic.qmd
      - name: Upload generated reports
        uses: actions/upload-artifact@v4
        with:
          name: simulation-reports
          path: analysis/_output/*
