name: Deploy Quarto Website to GitHub Pages

on:
  push:
    branches: 
      - main
    paths:
      - 'analysis/**'
      - '.github/workflows/quarto-deploy.yml'
  workflow_dispatch:

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shut_the_box_sim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.9"

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('shut_the_box_sim/uv.lock') }}

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Sync dependencies with uv
        run: uv sync --dev

      - name: Verify stbsim installation
        run: |
          uv run python -c "import stbsim; print('✅ stbsim imported successfully')"
          uv run python -c "from stbsim.simulation import Simulation; print('✅ Simulation class loaded')"

      - name: Render Quarto website
        run: |
          cd ../analysis
          QUARTO_PYTHON=../shut_the_box_sim/.venv/bin/python quarto render

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: analysis/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4